apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-cstb
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0074-tenant/tkrw-pr712-0075-0074-app/devfile-sample-cstb@sha256:e27ac3fa3a175c336c755c5fdcf7d0133e831458c308bb98123b34eaa5e7d8c4
        name: my-nodejs
        resources: {}
status: {}
